// Static editorial/marketing content from the original Kumbaya prototype
// (hero, "choose the kind of door" cards, mission section, editorial band,
// example output) - verbatim, unchanged. Kept as a single HTML blob rather
// than hand-converted to JSX since it's inert copy with no state or
// interactivity, so dangerouslySetInnerHTML carries zero behavioral risk
// here (unlike the form itself, which is a real Formik component - see
// KumbayaForm.tsx).
const KUMBAYA_STATIC_INTRO_HTML = `<header class="top"><div class="brand"><span class="mark"></span><span>Kumbaya</span></div><span class="tag">The Shared Upside Protocol · RampRate × ImpactSoul</span></header>
    <section class="hero"><div><div class="eyebrow">The Shared Upside Protocol · B Lab Certified</div><h1>Make the room worth more than its agenda.</h1><p>Kumbaya is our portfolio-wide impact and distribution intake. It helps us infuse possibility into an event, a company, a cause, or a story and increase the outcome for every constituency: organizers, sponsors, attendees, speakers, partners, and the communities they serve.</p></div><aside class="rulecard"><strong>A better kind of yes.</strong><p>One precise intake lets us route money, people, a speaker, a story, a publishing opportunity, a distribution channel, or the one introduction that changes the shape of the room.</p><div class="clock"><span class="dot"></span> Shared upside. Real participation. No logo confetti.</div><div class="clock" style="color:var(--violet2)"><span class="dot" style="background:var(--violet2);box-shadow:0 0 14px var(--violet2)"></span> One portfolio-wide form. Faster, more precise follow-through.</div></aside></section>
    <div class="hero-visual"><img src="https://cdn.sanity.io/images/xdo1fb5d/production/beb8cb7ea8c18035629a2158a89b4db67899d6f7-1942x809.png" alt="A diverse group gathered around a luminous shared table in a high-consequence room" /><div class="hero-visual-caption"><span>The room is only the beginning</span>What could move further because we were in it?</div></div>
    <section class="card" style="margin-bottom:28px"><div class="eyebrow">Choose the kind of door</div><h2 style="margin-top:9px">This is not a logo request.</h2><p class="sub">It is a quick way to design the most useful relationship around the event.</p><div class="choicegrid"><div class="route"><span class="pill">Bring leverage</span><h3>“We need the right sponsor.”</h3><p>We’ll look at audience, inventory, investment level, and sponsor fit.</p></div><div class="route"><span class="pill">Bring people</span><h3>“We need the right room.”</h3><p>We’ll look at who is attending, why they matter, and what introductions are appropriate.</p></div><div class="route"><span class="pill">Bring a voice</span><h3>“We need a speaker.”</h3><p>We’ll look at the slot, preparation, audience, and whether the invitation fits a portfolio theme.</p></div><div class="route"><span class="pill">Bring purpose</span><h3>“We need community support.”</h3><p>We’ll consider ImpactSoul, philanthropy, charitable support, and mission-aligned partners.</p></div></div><p style="color:var(--muted);margin:22px 0 0">The output is an internal fit card, an event overview in our eyes, and a sponsor-pitch prototype you can use whether or not we participate.</p></section>
    <section class="card" style="margin-bottom:28px"><div class="eyebrow">Why we enter a room</div><h2 style="margin-top:9px">Purpose before presence.</h2><p class="sub">RampRate and ImpactSoul are B Lab Certified businesses. That certification is part of our accountability, but the deeper test is what our choices do in the world. These are our intentions: the principles we use to decide where our time, money, relationships, and reputation belong.</p><div class="grid"><div class="route"><span class="pill">RampRate · mission</span><h3>Turn trust into useful leverage.</h3><p>We help founders, enterprises, and partners make better decisions, find the right relationships, reduce waste and extraction, and turn hard-to-navigate systems into workable progress.</p></div><div class="route"><span class="pill">ImpactSoul · mission</span><h3>Make purpose economically durable.</h3><p>We help missions, cultural assets, environmental stewardship, and communities become more visible, more fundable, and more capable of sustaining the work they exist to do.</p></div><div class="route"><span class="pill">Vision</span><h3>A more connected form of abundance.</h3><p>We want capital, technology, health, culture, and human possibility to reinforce one another instead of extracting value from the people and places they claim to serve.</p></div><div class="route"><span class="pill">Values</span><h3>Evidence. Alignment. Access. Care.</h3><p>We look for real fit, honest terms, inclusive access, measurable usefulness, responsible stewardship, and relationships that become stronger because we were involved.</p></div></div><div class="section"><h3>What this means for an event</h3><p class="sub" style="margin-bottom:0">We may participate when the room can create meaningful progress for a company, cause, community, or relationship. We may decline when the event is primarily logo extraction, vague networking, unverified claims, misaligned incentives, poor data permission, or a use of our name that does not reflect these intentions. A “no” is not a judgment on the people involved. It is a decision about fit, timing, responsibility, and where our involvement can genuinely help.</p></div></section>
    <div class="editorialband"><article><div class="eyebrow">What comes back</div><h3>A usable awareness brief</h3><p>We turn your answers into a concise story for sponsors, attendees, speakers, and partners, with a distribution plan instead of a vague promise to “share it.”</p></article><article><div class="eyebrow">How we track it</div><h3>From idea to signal</h3><p>When appropriate, our social team can adapt the story for the relevant channels, publish through our distribution network, and track reach, engagement, clicks, and follow-through in <a href="https://sproutsocial.com/" target="_blank" rel="noopener">Sprout Social</a>.</p></article><article><div class="eyebrow">Where this goes</div><h3>A living impact network</h3><p>As more portfolio companies and partner organizations use Kumbaya, the system can identify complementary audiences, channels, sponsors, speakers, and organizations worth connecting. The goal is a useful matching engine, not a database graveyard.</p></article></div><div class="example-output"><div class="eyebrow">Example output</div><h3>“A room where regenerative health becomes investable.”</h3><p>On October 18, the Future of Human Health gathering brings 300 clinicians, founders, investors, and community leaders together in Los Angeles. The opportunity is to connect mission-aligned sponsors with a serious audience, publish the story before the event, and create a post-event trail that keeps the best conversations moving. Suggested distribution: TonyGreenberg.com, partner newsletters, LinkedIn, selected PR relationships, and event-owned channels.</p><div class="footnote">* B Lab Certification means a business has been verified against B Lab’s standards for social and environmental performance, accountability, and transparency. <a href="https://www.bcorporation.net/en-us/find-a-b-corp/company/ramprate-a-team-inc/" target="_blank" rel="noopener">See RampRate A Team, Inc. in B Lab’s public directory</a>.</div></div>`;

export function KumbayaStaticIntro() {
  return <div dangerouslySetInnerHTML={{ __html: KUMBAYA_STATIC_INTRO_HTML }} />;
}
